spring:
  application:
    name: TheOpenBank
  datasource:
    url: jdbc:postgresql://localhost:5432/abcbank
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
